In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.array([[2,4,6,8,10],[1,3,5,7,9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

<style>
td {
  font-size: 500px
}
</style>
#Array Attributes - 7.3

In [8]:
floats = np.array([0.0, 0.1, 0.2, 0.3,0.4])
print("floats :",floats)
print("dtype :",floats.dtype)

floats : [0.  0.1 0.2 0.3 0.4]
dtype : float64


In [9]:
integers = np.array([[1, 2, 3], [4, 5,6]])
print("integers : ", integers)
print("dtype :",integers.dtype)

integers :  [[1 2 3]
 [4 5 6]]
dtype : int32


In [10]:
print("integers.ndim :",integers.ndim)
print("floats.ndim :",floats.ndim)
print("integers.shape :",integers.shape)
print("floats.shape :",floats.shape)
print("integers.size :",integers.size)
print("integers.itemsize :",integers.itemsize) # 4 if C compiler uses 32-bit ints
print("floats.size :",floats.size)
print("floats.itemsize :",floats.itemsize)

integers.ndim : 2
floats.ndim : 1
integers.shape : (2, 3)
floats.shape : (5,)
integers.size : 6
integers.itemsize : 4
floats.size : 5
floats.itemsize : 8


In [11]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [12]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

# Practise - 7.4

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones((2,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

# Practise - 7.5 

In [16]:
print("np.arange(6) :",np.arange(6))
print("np.arange(6,12) :",np.arange(6,12))
print("np.arange(10,1,-2) :",np.arange(10,1,-2))
print("np.linspace(0.0, 1.0, num=5) :",np.linspace(0.0, 1.0, num=5))
print("np.arange(1, 21).reshape(4, 5) :",np.arange(1, 21).reshape(4, 5))
print("np.arange(2, 40).reshape(4, 5) :",np.arange(2, 41,2).reshape(4, 5))

np.arange(6) : [0 1 2 3 4 5]
np.arange(6,12) : [ 6  7  8  9 10 11]
np.arange(10,1,-2) : [10  8  6  4  2]
np.linspace(0.0, 1.0, num=5) : [0.   0.25 0.5  0.75 1.  ]
np.arange(1, 21).reshape(4, 5) : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
np.arange(2, 40).reshape(4, 5) : [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


# Practise - 7.6 List vs Array

In [17]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

72.2 ms ± 5.95 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [18]:
%timeit sum([x for x in range(10_000_000)])

893 ms ± 42.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%timeit np.arange(10_000_000).sum()

21 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Practise - 7.7, 7.8, 7.9

In [20]:
numbers = np.arange(1,6)
print(numbers)
numbers * 2

[1 2 3 4 5]


array([ 2,  4,  6,  8, 10])

In [21]:
numbers**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [22]:
print(numbers)

[1 2 3 4 5]


In [23]:
numbers+=10
numbers

array([11, 12, 13, 14, 15])

In [24]:
numbers * [2,2,2,2,2]

array([22, 24, 26, 28, 30])

In [25]:
numbers2 = np.linspace(1.1,5.5,5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [26]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [27]:
print("numbers>=13 :",numbers>=13)
print("numbers2 <numbers :",numbers2 <numbers)
print("numbers == numbers2 :",numbers==numbers2)
print("numbers == numbers :",numbers==numbers)

numbers>=13 : [False False  True  True  True]
numbers2 <numbers : [ True  True  True  True  True]
numbers == numbers2 : [False False False False False]
numbers == numbers : [ True  True  True  True  True]


In [28]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)
grades

array([[ 97,  99, 100,  63],
       [ 83,  67,  98,  62],
       [ 71,  73,  78,  75]])

In [29]:
print("grades.mean() :",grades.mean())
print("grades.mean(axis=0) :",grades.mean(axis=0))
print("grades.mean(axis=1) :",grades.mean(axis=1))

grades.mean() : 80.5
grades.mean(axis=0) : [83.66666667 79.66666667 92.         66.66666667]
grades.mean(axis=1) : [89.75 77.5  74.25]


In [30]:
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [31]:
numbers2 = np.arange(1, 7) * 10
numbers2

array([10, 20, 30, 40, 50, 60])

In [32]:
print("np.add(numbers,numbers2) :",np.add(numbers,numbers2))
print("np.multiply(numbers2, 5) :",np.multiply(numbers2, 5))

np.add(numbers,numbers2) : [11 24 39 56 75 96]
np.multiply(numbers2, 5) : [ 50 100 150 200 250 300]


In [33]:
numbers3 = numbers2.reshape(2, 3)
print("numbers3 :",numbers3)
numbers4 = np.array([2, 4, 6])
print("numbers4 :",numbers4)
print("np.multiply(numbers3, numbers4) :",np.multiply(numbers3, numbers4))

numbers3 : [[10 20 30]
 [40 50 60]]
numbers4 : [2 4 6]
np.multiply(numbers3, numbers4) : [[ 20  80 180]
 [ 80 200 360]]


In [34]:
numbers_pow = np.arange(1, 6)
print("np.power(numbers_pow, 3) :",np.power(numbers_pow, 3))

np.power(numbers_pow, 3) : [  1   8  27  64 125]


In [35]:
sample = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15]])
print("Second Row :", sample[1])
print("First and Second :",sample[[0,2]])
print("Middle Three columns :",sample[:,1:4])

Second Row : [ 6  7  8  9 10]
First and Second : [[ 1  2  3  4  5]
 [11 12 13 14 15]]
Middle Three columns : [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
